#url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
browser=chrome
#username=Admin
#password=admin123
#Time in Seconds
implicitwait=10
#local
local.url=http://localhost/orangehrm/web/index.php/auth/login
local.username=admin
local.password=Admin$$124